# Generated by Django 6.0 on 2025-12-17 09:27

import common.enums.roles_user
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='DE'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'renter'), ('landlord', 'landlord')], default=common.enums.roles_user.Roles['RENTER'], max_length=50),
        ),
    ]
