# Generated by Django 6.0 on 2025-12-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('property_type', models.CharField(choices=[('FLAT', 'FLAT'), ('HOUSE', 'HOUSE'), ('STUDIO', 'STUDIO'), ('ROOM', 'ROOM')], max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
