# Generated by Django 6.0 on 2025-12-13 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('listing', 'user', 'check_in', 'check_out'), name='unique_booking_user_listing_dates'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('listing', 'user', 'check_in', 'check_out')},
        ),
    ]
