# Generated by Django 6.0 on 2025-12-17 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('listings', '0003_alter_listing_is_active_alter_listing_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_user_listing_dates',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='renter',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('listing', 'renter', 'check_in', 'check_out')},
        ),
    ]
